services:
  api:
    build: ./api
    command: npm run dev  # Gebruik nodemon voor live updates
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://admin:secretpassword@db:27017?authSource=admin
      - DB_NAME=mydb
    volumes:
      - ./api:/app        # Mount de code voor live updates
      - /app/node_modules # Voorkom dat lokale node_modules de container overschrijven
    depends_on:
      db:
        condition: service_started

  db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - mongo-data:/data/db
      - ./mongo-init/seed.js:/docker-entrypoint-initdb.d/seed.js:ro

  client:
    build: ./client
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api

volumes:
  mongo-data:
